<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>b_Code_SE</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Interop.SolidEdgeFramework">
      <HintPath>lib\Interop.SolidEdgeFramework.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Interop.SolidEdgeConstants">
      <HintPath>lib\Interop.SolidEdgeConstants.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Interop.SolidEdgePart">
      <HintPath>lib\Interop.SolidEdgePart.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>